apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-demo-staging
  namespace: argocd
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/cicd-gitops-demo.git
    targetRevision: HEAD
    path: gitops-repo/environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 