# Custom values for the bitnami/nginx Helm chart
# This file provides a complete and working set of initial configurations for deploying Nginx.
# LAB.md will guide you through modifying specific values below as part of the lab exercises.

# --- Core Configuration ---
# These are the primary values you might interact with during the lab.

replicaCount: 1
# LAB.md will instruct you to modify the 'replicaCount'.

image:
  # The repository is typically set by the Helm chart itself (e.g., bitnami/nginx).
  # repository: bitnami/nginx
  tag: "1.25.3" # Specifies a particular version of Nginx.
  # LAB.md may instruct you to change this tag or comment it out to use the chart's default.
  pullPolicy: IfNotPresent
  debug: false
  # LAB.md may instruct you to set 'debug' to true for troubleshooting exercises.

service:
  type: NodePort
  # LAB.md will instruct you to confirm the service 'type'.
  port: 80 # Port exposed on the service's internal cluster IP.
  # targetPort: http # Typically defaults to 80 for Nginx.
  nodePort: 30080
  # LAB.md will instruct you to modify the 'nodePort'.
  # If 'nodePort' is null or not specified, a port will be auto-assigned from the NodePort range.

# --- Optional Advanced Configurations (Examples for Exploration) ---
# The following sections are well-formed examples of advanced configurations.
# They are commented out by default and are for your learning and exploration.
# LAB.md will specify if any part of these sections needs to be uncommented and used.
# Refer to the official bitnami/nginx Helm chart documentation for all available options.

# ingress:
#   enabled: false
#   # className: "" # Uncomment and specify if you have a specific IngressClass
#   hostname: nginx.example.com # Replace with your desired FQDN
#   path: /
#   pathType: ImplementationSpecific
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # nginx.ingress.kubernetes.io/rewrite-target: /
#   tls: []
#   #  - secretName: nginx-example-tls
#   #    hosts:
#   #      - nginx.example.com

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

# --- Further Customizations ---
# Any other specific chart values can be overridden here.
# All modifications for this lab's exercises will be explicitly guided by LAB.md. 