apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-production
  namespace: argocd
  labels:
    environment: production
spec:
  project: default
  source:
    repoURL: YOUR_GIT_REPO_URL_HERE
    targetRevision: HEAD
    path: environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-production
  syncPolicy:
    manual: {}
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m 