apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-production
  labels:
    app: webapp
    environment: production
spec:
  type: NodePort
  selector:
    app: webapp
    environment: production
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
    protocol: TCP
    name: http 