apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-global-triggers
  namespace: argocd
data:
  # Global out-of-sync trigger (all environments)
  trigger.on-out-of-sync: |
    - when: app.status.sync.status != 'Synced'
      send: [app-out-of-sync]
  
  # Global health recovery trigger
  trigger.on-health-recovered: |
    - when: app.status.health.status == 'Healthy' and app.status.health.previousStatus != 'Healthy'
      send: [app-health-recovered] 