apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-production-triggers
  namespace: argocd
data:
  # Production sync failure trigger
  trigger.on-sync-failed-production: |
    - when: app.status.operationState.phase in ['Error', 'Failed'] and app.metadata.labels.environment == 'production'
      send: [production-alert]
  
  # Production health degradation trigger
  trigger.on-health-degraded-production: |
    - when: app.status.health.status != 'Healthy' and app.metadata.labels.environment == 'production'
      send: [production-alert]
  
  # Production sync success (for important deployments)
  trigger.on-sync-succeeded-production: |
    - when: app.status.operationState.phase == 'Succeeded' and app.metadata.labels.environment == 'production'
      send: [app-sync-succeeded]
  
  # Notifiers configuration
  service.slack: |
    token: $slack-webhook-url 