apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-staging-triggers
  namespace: argocd
data:
  # Staging sync events
  trigger.on-sync-failed-staging: |
    - when: app.status.operationState.phase in ['Error', 'Failed'] and app.metadata.labels.environment == 'staging'
      send: [app-sync-failed]
  
  trigger.on-sync-succeeded-staging: |
    - when: app.status.operationState.phase == 'Succeeded' and app.metadata.labels.environment == 'staging'
      send: [staging-notification]
  
  # Staging health events
  trigger.on-health-degraded-staging: |
    - when: app.status.health.status != 'Healthy' and app.metadata.labels.environment == 'staging'
      send: [app-health-degraded] 