version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5003:5000" # Using host port 5003 for this lab to avoid conflict with Lab02 if running simultaneously
    # TODO_VOLUMES_DEV: Mount the local './app' directory to '/usr/src/app' in the container.
    # This enables live code reloading: changes made to your local ./app directory
    # will be immediately reflected in the container without rebuilding the image.
    # Syntax: volumes: - <host_path>:<container_path>
    volumes:
      - ./app:/usr/src/app # Example, student needs to understand and verify or implement this line.

    # TODO_ENVIRONMENT_DEV: Set environment variables for development mode.
    # For Flask, `FLASK_ENV=development` or `FLASK_DEBUG=1` enables debug mode and the reloader.
    # The `main.py` in this lab is set up to pick up these standard Flask environment variables.
    # Also, ensure REDIS_HOST is set for the app to connect to the redis service.
    # Syntax: environment: - VARIABLE_NAME=value OR environment: VARIABLE_NAME: value
    environment:
      - REDIS_HOST=redis
      # - FLASK_ENV=development  # Example: Student needs to add/uncomment and choose one (or FLASK_DEBUG)
      # - FLASK_DEBUG=1          # Example: Student needs to add/uncomment and choose one (or FLASK_ENV)

    depends_on:
      - redis

  redis:
    image: "redis:6-alpine"
    ports:
      - "6381:6379" # Optional: Exposing Redis on a different host port (6381) for this lab
    # volumes: # Optional: For Redis data persistence. Not the focus of this dev environment lab.
    #  - redis_lab03_data:/data

# Optional: Define a named volume if you uncommented it for Redis persistence
# volumes:
#   redis_lab03_data: 