apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app
  namespace: cicd-production
  labels:
    app: cicd-demo
    environment: production
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-demo
      environment: production
  template:
    metadata:
      labels:
        app: cicd-demo
        environment: production
        version: v1.0.0
    spec:
      containers:
      - name: app
        image: YOUR_DOCKERHUB_USERNAME/cicd-demo:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "v1.0.0"
        - name: ENVIRONMENT
          value: "production"
        - name: BUILD_DATE
          value: "2024-01-01T00:00:00Z"
        - name: GIT_COMMIT
          value: "unknown"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
  namespace: cicd-production
  labels:
    app: cicd-demo
    environment: production
spec:
  type: NodePort
  selector:
    app: cicd-demo
    environment: production
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30200
    protocol: TCP
    name: http 