apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namespace: cicd-production

commonLabels:
  app: cicd-demo
  environment: production
  managed-by: argocd

images:
- name: YOUR_DOCKERHUB_USERNAME/cicd-demo
  newTag: v1.0.0 