apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      serviceAccountName: argocd-notifications-controller
      containers:
      - name: argocd-notifications-controller
        image: quay.io/argoproj/argocd:v2.8.4
        command:
        - argocd-notifications
        - controller
        env:
        - name: ARGOCD_NOTIFICATIONS_CONTROLLER_METRICS_ENABLED
          value: "true"
        - name: ARGOCD_NOTIFICATIONS_CONTROLLER_METRICS_PORT
          value: "9001"
        ports:
        - containerPort: 9001
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: notifications-config
          mountPath: /etc/argocd-notifications
        - name: argocd-repo-server-tls
          mountPath: /app/config/server/tls
      volumes:
      - name: notifications-config
        configMap:
          name: argocd-notifications-cm
      - name: argocd-repo-server-tls
        secret:
          secretName: argocd-repo-server-tls
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller
spec:
  selector:
    app.kubernetes.io/name: argocd-notifications-controller
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
    targetPort: 9001 