apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-demo-app
  labels:
    app: sync-demo
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sync-demo
  template:
    metadata:
      labels:
        app: sync-demo
        version: v1.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: sync-demo-config
              key: app.mode
        - name: SYNC_POLICY
          value: "MANUAL"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 