apiVersion: v1
kind: Service
metadata:
  name: sync-demo-service
  labels:
    app: sync-demo
spec:
  type: NodePort
  selector:
    app: sync-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30095
    protocol: TCP
    name: http 