apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-health-cm
  namespace: argocd
data:
  # Slack template for health degradation
  template.app-health-degraded: |
    slack:
      title: "🔴 Application Health Degraded"
      text: |
        Application **{{.app.metadata.name}}** health has degraded to **{{.app.status.health.status}}**.
        
        *Environment:* {{.app.metadata.labels.environment | default "unknown"}}
        *Previous Health:* Healthy
        *Current Health:* {{.app.status.health.status}}
        *Message:* {{.app.status.health.message | default "No additional details"}}
      color: "danger"
      attachments: |
        [{
          "title": "Health Status Details",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "danger",
          "fields": [
            {
              "title": "Health Status",
              "value": "{{.app.status.health.status}}",
              "short": true
            },
            {
              "title": "Environment",
              "value": "{{.app.metadata.labels.environment | default \"unknown\"}}",
              "short": true
            },
            {
              "title": "Health Message",
              "value": "{{.app.status.health.message | default \"No additional details\"}}",
              "short": false
            }
          ]
        }]
  
  # Slack template for health recovery
  template.app-health-recovered: |
    slack:
      title: "✅ Application Health Recovered"
      text: |
        Application **{{.app.metadata.name}}** has recovered and is now **{{.app.status.health.status}}**.
        
        *Environment:* {{.app.metadata.labels.environment | default "unknown"}}
        *Health Status:* {{.app.status.health.status}}
      color: "good" 