apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-demo-app
  labels:
    app: secrets-demo
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secrets-demo
  template:
    metadata:
      labels:
        app: secrets-demo
        version: v1.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        # Environment variables from regular secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: api-key
        # Environment variables from sealed secret
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-token
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: encryption-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        # Mount secrets as files
        volumeMounts:
        - name: secret-files
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-files
        secret:
          secretName: app-secrets 