# WARNING: This is an example of INSECURE secret storage!
# DO NOT commit secrets like this to Git repositories in production!
# This example demonstrates why we need Sealed Secrets or external secret management.

apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  labels:
    app: secrets-demo
type: Opaque
data:
  # These values are base64 encoded but NOT encrypted!
  # Anyone with access to Git can decode these easily:
  # echo "cGFzc3dvcmQxMjM=" | base64 -d  # reveals "password123"
  # echo "YWJjZGVmZ2hpams=" | base64 -d  # reveals "abcdefghijk"
  password: cGFzc3dvcmQxMjM=    # password123
  api-key: YWJjZGVmZ2hpams=     # abcdefghijk 