# This is an example of a Sealed Secret - encrypted and safe for Git storage
# This file will be generated during the lab using the kubeseal tool
# The actual sealed secret will contain encrypted data that only the 
# Sealed Secrets controller can decrypt

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: secrets-demo-app
spec:
  encryptedData:
    # These values are encrypted using the Sealed Secrets controller's public key
    # They will be generated during the lab and will look like this:
    # secret-token: AgBy3i4OJSWK+PiTySYZZA9rO33HzxcpRaS...
    # encryption-key: AgAaX9g5h2kL+8mN4oP6qR7s3T9vW1xY2z...
    secret-token: PLACEHOLDER_WILL_BE_GENERATED_IN_LAB
    encryption-key: PLACEHOLDER_WILL_BE_GENERATED_IN_LAB
  template:
    metadata:
      name: app-secrets
      namespace: secrets-demo-app
    type: Opaque 