apiVersion: v1
kind: Service
metadata:
  name: secrets-demo-service
  labels:
    app: secrets-demo
spec:
  type: NodePort
  selector:
    app: secrets-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
    protocol: TCP
    name: http 