apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-app-deployment
  labels:
    app: my-custom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-custom-app
  template:
    metadata:
      labels:
        app: my-custom-app
    spec:
      containers:
      - name: my-custom-app-container
        image: your-dockerhub-username/my-custom-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000 