apiVersion: v1
kind: Service
metadata:
  name: my-custom-app-service
  labels:
    app: my-custom-app
spec:
  type: NodePort 
  selector:
    app: my-custom-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000