apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-google
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: "http://localhost:8080"
  server.insecure: "true"
  
  # Google OIDC configuration
  oidc.config: |
    name: Google
    issuer: https://accounts.google.com
    clientId: YOUR_GOOGLE_CLIENT_ID
    clientSecret: YOUR_GOOGLE_CLIENT_SECRET
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  
  # Dex configuration for Google
  dex.config: |
    connectors:
    - type: oidc
      id: google
      name: Google
      config:
        issuer: https://accounts.google.com
        clientID: YOUR_GOOGLE_CLIENT_ID
        clientSecret: YOUR_GOOGLE_CLIENT_SECRET
        redirectURI: http://localhost:8080/api/dex/callback
        hostedDomains:
        - your-company.com 