apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-demo-app
  labels:
    app: rollback-demo
    version: v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollback-demo
  template:
    metadata:
      labels:
        app: rollback-demo
        version: v3
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "v3.0.0"
        - name: APP_MESSAGE
          value: "Version 3 - FIXED: Issues resolved, improved performance"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: rollback-demo-service
  labels:
    app: rollback-demo
spec:
  type: NodePort
  selector:
    app: rollback-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090 