apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-email-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: "your-email@example.com"
  email-password: "your-app-password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-email-cm
  namespace: argocd
data:
  service.email: |
    host: smtp.gmail.com
    port: 587
    from: your-email@example.com
    username: $email-username
    password: $email-password
  
  template.app-sync-failed-email: |
    email:
      subject: "ArgoCD: Application {{.app.metadata.name}} sync failed"
      body: |
        Application {{.app.metadata.name}} sync failed.
        
        Repository: {{.app.spec.source.repoURL}}
        Environment: {{.app.metadata.labels.environment | default "unknown"}}
        Error: {{.app.status.operationState.message}}
        
        View in ArgoCD: {{.context.argocdUrl}}/applications/{{.app.metadata.name}} 