apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-staging
  labels:
    app: webapp
    environment: staging
spec:
  type: NodePort
  selector:
    app: webapp
    environment: staging
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http 